#!/bin/sh
# SETUP:
# 
# 1. ADD alias to 
# vim ~/.bash_profile
# 
# alias hayatapp="sh /Users/dieskim/Dropbox/BOX_Data/Bible_Apps/studio_app_workspace/hayatapp/custom-cli"
# 
# 2. RELEAD BASH
# 
# . ~/.bash_profile
# 
# 3. RUN COMMANDS
# 
#  hayatapp-cli clean
#  hayatapp-cli doc
#  hayatapp-cli subtree
#  hayatapp-cli build

script_full_path=$(dirname "$0")

clean (){
   
    cd $script_full_path
    rm -fR build
    rm -fR Resources
    rm -fR i18n
    rm -fR platform
    echo "==== APP CLEAN COMPLETE ====";

}

doc(){

    echo "==== START JSDOC CREATION ====";
    cd $script_full_path
    jsdoc app -r -c jsdoc_conf.json -d docs
    echo "==== END JSDOC CREATION ====";

}

subtree(){
    
    cd $script_full_path
    sh git-subtree $1 $2

}

build(){

    providedDevice=$1
    buildDevice=${providedDevice:=iphone6}

    if [ $buildDevice == 'iphone6' ]
    then

        #build iphone6
        appc run --skip-js-minify --log-level trace -p ios -C 72ED9DD5-E26C-4BB9-9559-AC95A1295302 -d $script_full_path

    elif [ $buildDevice == 'iphoneX' ]
    then

        #build iphoneX
        appc run --skip-js-minify --log-level trace -p ios -C 7CFD66C1-C54D-4555-950A-6FBCB67C5D80 -d $script_full_path

    elif [ $buildDevice == 'iphoneCM' ]
    then

        #build iphoneCM
        aappc run --skip-js-minify --log-level trace -p ios -T device -V 'Jack Ma (2D3D5P9559)' -P f5f9c0bd-b9a1-43cb-a514-9760e6d49e1b -C f9c33ff0f5a327b9c9f88af2a3375902b12a6cbf -d $script_full_path

    elif [ $buildDevice == 'ipadCM' ]
    then

        #build ipadCM
        appc run --skip-js-minify --log-level trace -p ios -T device -V 'Jack Ma (2D3D5P9559)' -P f5f9c0bd-b9a1-43cb-a514-9760e6d49e1b -C 0f21d8c06b786149f0524a76fe671cbd19599891 -d $script_full_path

    elif [ $buildDevice == 'android6' ]
    then
        
        #build android6
        appc run  --skip-js-minify --log-level trace -p android -C 'Google Nexus 5 - 6.0.0 - API 23 - 1080x1920' -d $script_full_path

    elif [ $buildDevice == 'A1' ]
    then
        
        #build A1
        appc run  --skip-js-minify --log-level trace -p android -T device -C 0364d38f0504 -d $script_full_path

    elif [ $buildDevice == 'Nexus7' ]
    then
        
        #build A1
        appc run  --skip-js-minify --log-level trace -p android -T device -C 08792765 -d $script_full_path

    fi
}
# Check if the function exists (bash specific)
if declare -f "$1" > /dev/null
then
    # call arguments verbatim
    "$@"
else
    # Show a helpful error
    echo "Unknown Function";
    echo "Please spesify a Valid Function:" >&2
    echo "-------------------------"
    echo "To Clean App:";
    echo "sh custom-cli clean";
    echo "-------------------------"
    echo "To Build jsdoc:";
    echo "sh custom-cli doc";
    echo "-------------------------"
    echo "To Run Git Subtree:";
    echo "sh custom-cli subtree";
    echo "-------------------------"
    echo "To Build App Run:";
    echo "sh custom-cli build iphone6";
    echo "-------------------------"

  exit 1
fi